### PR TITLE
Add an assigment-add operator (+=)

### PR DESCRIPTION
**Pull request by PetterS**
This would have been useful in Project Gödel.

No modifications to the IR, just the compiler.

If this is OK, I can add `-=` etc. as well.

### CODE REVIEW

**Comment by jsannemo** [comment]
@PetterS  I'm rewriting the frontend in order to be cross-compilable to JavaScript (to replace the VS Code plugin with an online editor), but will make sure to include += and ++ in the new version!

**Comment by PetterS** [comment]
Online editor like repl.it or something would be awesome

**Comment by jsannemo** [comment]
Yep, that's the plan. I noticed yesterday that https://github.com/google/j2cl/ was opensourced now, so the plan is to use that to compile the compiler, VM and test harnesses to JS.

**Comment by jsannemo** [comment]
Parser is now rewritten; += added.

It will probably not make it into a new build for a while, since I'm focusing on fixing a web editor

**Pull request closed without merging**
